- name: "Install snap packages"
  snap:
    name: "{{ item }}"
    classic: yes
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ snaps }}"
  tags:
    - "snap"
    - "development"

- name: "Install neovim snap package"
  snap:
    name: "nvim"
    classic: yes
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - "nvim"