- name: Add Elixir plugin with asdf
  command: "asdf plugin-add elixir"
  register: elixir_add
  failed_when: elixir_add == 2

- name: "Install elixir versions"
  command: asdf install elixir {{item}}
  loop: "{{versions}}"

- name: Set global version for elixir to {{versions[0]}}
  command: "asdf global elixir {{versions[0]}}"