- name: "Check if .bash_aliases exists"
  stat: path="{{dotfiles_user_home}}/.bash_aliases"
  register: alias_stat
  tags:
    - "bash"

- name: "Back up .bash_aliases"
  command: mv {{dotfiles_user_home}}/.bash_aliases {{dotfiles_user_home}}/.bash_aliases.bak
  args:
    creates: "{{dotfiles_user_home}}/.bash_aliases.bak"
  when: alias_stat.stat.exists
  tags:
    - "bash"

- name: "Move new .bash_aliases"
  command: mv {{ dotfiles_home }}/alias {{dotfiles_user_home}}/.bash_aliases
  tags:
    - "bash"