---
# tasks/main.yml for flathub



## Repository Management

- name: "Manage flathub Repository"
  community.general.flatpak_remote:
    name: "{{ flathub_repository_name }}"
    state: "{{ flathub_repository_state }}"
    flatpakrepo_url: "{{ flathub_repository_url }}"
    method: "{{ flathub_repository_method }}"
  become: true
  tags:
    - "flathub"
    - "repository"

## Dependency Management
- name: "Install GIMP Flatpak"
  community.general.flatpak:
    name: "org.gimp.GIMP"
    state: "present"
  become: true
  tags:
    - "flathub"
    - "photo"
...