---
# tasks/main.yml for flathub

## Repository Management

- name: "Manage flathub Repository"
  community.general.flatpak_remote:
    name: "{{ flathub_repository_name }}"
    state: "{{ flathub_repository_state }}"
    flatpakrepo_url: "{{ flathub_repository_url }}"
    method: "{{ flathub_repository_method }}"
  become: true
  tags:
    - "repository"

## Dependency Management
- name: "Install GIMP Flatpak"
  community.general.flatpak:
    name: "org.gimp.GIMP"
    state: "present"
  become: true
  tags:
    - "photo"

- name: "Install FontForge Flatpak"
  community.general.flatpak:
    name: "org.fontforge.FontForge"
    state: "present"
  become: true
  tags:
    - "font"

- name: "Install Amazon Workspace Flatpak"
  community.general.flatpak:
    name: "com.amazon.Workspaces"
    state: "present"
  become: true
  tags:
    - "aws"
    - "development"
    - "cloud"

- name: "Install Arduino IDE Flatpak"
  community.general.flatpak:
    name: "cc.arduino.arduinoide"
    state: "present"
  become: true
  tags:
    - "arduino"
    - "development"
    - "ide"

- name: "Install Fritzing Flatpak"
  community.general.flatpak:
    name: "org.fritzing.Fritzing"
    state: "present"
  become: true
  tags:
    - "arduino"
    - "development"
    - "ide"

- name: "Install Insomnia Flatpak"
  community.general.flatpak:
    name: "rest.insomnia.Insomnia"
    state: "present"
  become: true
  tags:
    - "development"

- name: "Install Zoom Flatpak"
  community.general.flatpak:
    name: "us.zoom.Zoom"
    state: "present"
  become: true
  tags:
    - "zoom"

- name: "Install MS Teams Flatpak"
  community.general.flatpak:
    name: "com.microsoft.Teams"
    state: "present"
  become: true
  tags:
    - "teams"

    # com.microsoft.Teams
...