- name: "Install git"
  apt: name=git state=present
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - "repository"
    - "development"

- name: "Link global gitignore file"
  file:
    src: "{{ dotfiles_home }}/gitignore_global.link"
    dest: "{{ dotfiles_user_home }}/.gitignore_global"
    state: link
    force: yes
  tags:
    - "repository"
    - "development"

- name: "Check if gitconfig exists"
  stat: path="{{dotfiles_user_home}}/.gitconfig"
  register: gitconfig_stat
  tags:
    - "repository"
    - "development"

- name: "Back up gitconfig"
  command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
    creates: "{{dotfiles_user_home}}/.gitconfig.bak"
  when: gitconfig_stat.stat.exists
  tags:
    - "repository"
    - "development"

- name: "Make sure gitconfig is up to date"
  template:
    src: "gitconfig.j2"
    dest: "{{dotfiles_user_home}}/.gitconfig"
  tags:
    - "repository"
    - "development"
