- name: Add nodejs plugin to asdf [https://github.com/asdf-vm/asdf-nodejs]
  command: "asdf plugin-add nodejs"
  register: node_add
  failed_when: node_add == 2

# - name: Import OpenPGP key
#   command: "bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring"

- name: Install nodejs with asdf
  command: asdf install nodejs {{item}}
  loop: "{{versions}}"

- name: Set global version for nodejs to {{default_version}}
  command: "asdf global nodejs {{default_version}}"


- name: Install "yarn" node.js package globally
  npm:
    name: yarn
    global: yes
  tags:
    - "yarn"
